name: Build on Ubuntu
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: My first Hello World action
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
